In [20]:
import pandas as pd
# lectura de archivos
serieA = pd.read_csv("../../SerieA2024.csv", sep=";")  # Ensure the file is in the same directory as the notebook

serieBS = pd.read_csv("../../SerieBS2024.csv", sep=";")

# cargar hospitales 2024
hospitales = pd.read_csv("2024_hospitals.csv")

In [21]:
# seleccionar los valores distintos que hay en la columna IdEstablecimiento
xd = serieA['IdEstablecimiento'].unique()
xd

array([105402, 201326, 105100, ..., 200086, 110140, 201666])

In [22]:
# seleccionar 10 datos aleatorios de la serie A
serieA.sample(10, random_state=1)  # random_state for reproducibility

,Mes,IdServicio,Ano,IdEstablecimiento,CodigoPrestacion,IdRegion,IdComuna,Col01,Col02,Col03,...,Col41,Col42,Col43,Col44,Col45,Col46,Col47,Col48,Col49,Col50
5457844,5,24,2024,124105,07020801,10,10101,180.0,33.0,53.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
647846,2,21,2024,121309,26273107,9,9101,6.0,4.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5719587,10,25,2024,125418,04025030,11,11201,24.0,0.0,24.0,...,0.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
947356,2,21,2024,121312,01090060,9,9117,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1924276,8,10,2024,110160,19190101,13,13503,2.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6035805,1,4,2024,104103,09600370,3,3301,63.0,21.0,42.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4397161,1,3,2024,200508,28022420,2,2101,110.0,41.0,69.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
814875,3,21,2024,121120,09400082,9,9109,347.0,150.0,197.0,...,10.0,5.0,3.0,0.0,11.0,0.0,0.0,NaN,NaN,NaN
1498592,10,33,2024,133160,07021700,10,10210,43.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5876265,4,6,2024,106319,02010420,5,5601,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# seleccionar primeras 15 columnas de la serie A
serieA = serieA.iloc[:, :15]

In [24]:
serieA.head(10)  # Display first 10 rows of the DataFrame

,Mes,IdServicio,Ano,IdEstablecimiento,CodigoPrestacion,IdRegion,IdComuna,Col01,Col02,Col03,Col04,Col05,Col06,Col07,Col08
0,4,5,2024,105402,09600390,4,4101,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1,4,5,2024,105402,09600392,4,4101,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
2,4,5,2024,105402,09600394,4,4101,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN
3,4,5,2024,105402,08210005,4,4101,15.0,6.0,9.0,1.0,2.0,NaN,NaN,NaN
4,4,5,2024,105402,09400082,4,4101,91.0,36.0,55.0,NaN,NaN,NaN,1.0,NaN
5,2,5,2024,201326,05990043,4,4101,2.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN
6,4,5,2024,105100,29101723,4,4101,25.0,0.0,7.0,18.0,NaN,NaN,NaN,NaN
7,4,5,2024,105100,29101724,4,4101,54.0,0.0,16.0,38.0,NaN,NaN,NaN,NaN
8,4,5,2024,105100,29101725,4,4101,6.0,0.0,0.0,6.0,NaN,NaN,NaN,NaN
9,4,5,2024,105100,29101726,4,4101,44.0,0.0,12.0,32.0,NaN,NaN,NaN,NaN

In [25]:
cols_to_sum = ['Col01', 'Col02', 'Col03', 'Col04', 'Col05', 'Col06', 'Col07', 'Col08']
serieA = (
    serieA
    .groupby(['IdServicio','Ano', 'IdEstablecimiento', 'CodigoPrestacion', 'IdRegion','IdComuna'], as_index=False)
    .agg({
        **{c: 'sum'    for c in cols_to_sum},
        'IdRegion':  'first',
        'IdComuna':  'first'
    })
)

In [26]:
serieA.head(10)  # Display first 10 rows of the DataFrame

,IdServicio,Ano,IdEstablecimiento,CodigoPrestacion,Col01,Col02,Col03,Col04,Col05,Col06,Col07,Col08,IdRegion,IdComuna
0,1,2024,101010,05224900,5.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,15,15101
1,1,2024,101010,05227400,5.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,15,15101
2,1,2024,101010,05810140,6.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,15,15101
3,1,2024,101010,05810441,5.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,15,15101
4,1,2024,101010,05810442,6.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,15,15101
5,1,2024,101010,05810445,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,15,15101
6,1,2024,101010,05810446,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,15,15101
7,1,2024,101010,05990036,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,15,15101
8,1,2024,101010,06020201,359.0,229.0,130.0,0.0,0.0,0.0,0.0,0.0,15,15101
9,1,2024,101010,06020202,1000.0,284.0,716.0,0.0,0.0,0.0,0.0,95.0,15,15101

Calcular consultas

In [27]:
# cargar archivo consultas
consultas = pd.read_csv("./variables/2024_consultas.txt")

# obtener nombres de las columnas
consultas = consultas.columns.tolist()

# eliminar primer elemento de la lista
consultas = consultas[1:]

# eliminar primer caracter de cada elemento de la lista
consultas = [c[1:] for c in consultas]

# obtener filas de la serie A que tengan los valores de consultas en la columna CodigoPrestacion
serieA_consultas = serieA[serieA['CodigoPrestacion'].isin(consultas)]

cols_to_sum = ['Col01']

# acumular columnas en una sola columna llamada Consultas
serieA_consultas['Consultas'] = serieA_consultas[cols_to_sum].sum(axis=1)

serieA_consultas = (
    serieA_consultas
    .groupby(
        ['IdServicio','Ano','IdEstablecimiento',
         'IdRegion','IdComuna'],
        as_index=False
    )['Consultas']
    .sum()
)

# cruzar serieA con hospitales según IdEstablecimiento
hospitales = pd.merge(hospitales, serieA_consultas[['IdEstablecimiento', 'Consultas']], left_on='hospital_id', right_on='IdEstablecimiento', how='left')

# eliminar columna IdEstablecimiento
hospitales = hospitales.drop(columns=['IdEstablecimiento'])

C:\Users\roesc\AppData\Local\Temp\ipykernel_8664\4125538195.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  serieA_consultas['Consultas'] = serieA_consultas[cols_to_sum].sum(axis=1)

Calcular quirofanos

In [28]:
# # cargar archivo consultas
quirofanos = pd.read_csv("./variables/2024_quirofanos.txt", header=None)

# quirofanos = pd.read_csv('./variables/2024_quirofanos.txt', header=None).transpose()

# # obtener nombres de las columnas
# quirofanos = quirofanos.columns.tolist()

# eliminar primer elemento de la lista
quirofanos = quirofanos[1:]

# pasar valores a string
quirofanos = quirofanos[0].astype(str)

# # eliminar primer caracter de cada elemento de la lista
quirofanos = [c[1:] for c in quirofanos]

# obtener filas de la serie A que tengan los valores de consultas en la columna CodigoPrestacion
serieA_quirofanos = serieA[serieA['CodigoPrestacion'].isin(quirofanos)]

cols_to_sum = ['Col01', 'Col02', 'Col03', 'Col04', 'Col05', 'Col06', 'Col07', 'Col08']

# acumular columnas en una sola columna llamada Consultas
serieA_quirofanos['Quirofanos'] = serieA_quirofanos[cols_to_sum].sum(axis=1)

serieA_quirofanos = (
    serieA_quirofanos
    .groupby(
        ['IdServicio','Ano','IdEstablecimiento',
         'IdRegion','IdComuna'],
        as_index=False
    )['Quirofanos']
    .sum()
)

# cruzar serieA con hospitales según IdEstablecimiento
hospitales = pd.merge(hospitales, serieA_quirofanos[['IdEstablecimiento', 'Quirofanos']], left_on='hospital_id', right_on='IdEstablecimiento', how='left')

# eliminar columna IdEstablecimiento
hospitales = hospitales.drop(columns=['IdEstablecimiento'])

C:\Users\roesc\AppData\Local\Temp\ipykernel_8664\3907902202.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  serieA_quirofanos['Quirofanos'] = serieA_quirofanos[cols_to_sum].sum(axis=1)

Calcular Consultas urgencias

In [29]:
# # cargar archivo consultas
consultas_urgencias = pd.read_csv("./variables/2024_consultas_urgencias.txt", header=None)

# eliminar primer elemento de la lista
consultas_urgencias = consultas_urgencias[1:]

# pasar valores a string
consultas_urgencias = consultas_urgencias[0].astype(str)

# # eliminar primer caracter de cada elemento de la lista
consultas_urgencias = [c[1:] for c in consultas_urgencias]

# obtener filas de la serie A que tengan los valores de consultas en la columna CodigoPrestacion
serieA_consultas_urgencias = serieA[serieA['CodigoPrestacion'].isin(consultas_urgencias)]

cols_to_sum = ['Col01']

# acumular columnas en una sola columna llamada Consultas
serieA_consultas_urgencias['Consultas Urgencias'] = serieA_consultas_urgencias[cols_to_sum].sum(axis=1)

serieA_consultas_urgencias = (
    serieA_consultas_urgencias
    .groupby(
        ['IdServicio','Ano','IdEstablecimiento',
         'IdRegion','IdComuna'],
        as_index=False
    )['Consultas Urgencias']
    .sum()
)

# cruzar serieA con hospitales según IdEstablecimiento
hospitales = pd.merge(hospitales, serieA_consultas_urgencias[['IdEstablecimiento', 'Consultas Urgencias']], left_on='hospital_id', right_on='IdEstablecimiento', how='left')

# eliminar columna IdEstablecimiento
hospitales = hospitales.drop(columns=['IdEstablecimiento'])

C:\Users\roesc\AppData\Local\Temp\ipykernel_8664\2605947785.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  serieA_consultas_urgencias['Consultas Urgencias'] = serieA_consultas_urgencias[cols_to_sum].sum(axis=1)

Calcular examenes

In [30]:
# import pandas as pd
# serieBS = pd.read_csv("../../SerieBS2024.csv", sep=";")

In [31]:
# # cargar archivo consultas
examenes = pd.read_csv("./variables/2024_examenes.txt", header=None)

# eliminar primer elemento de la lista
examenes = examenes[1:]

# pasar valores a string
examenes = examenes[0].astype(str)

# eliminar primer caracter de cada elemento de la lista
examenes = [c[1:] for c in examenes]

# pasar valores a int
examenes = [int(c) for c in examenes]

# obtener filas de la serie A que tengan los valores de consultas en la columna CodigoPrestacion
serieBS_examenes = serieBS[serieBS['CodigoPrestacion'].isin(examenes)]

cols_to_sum = ['Col01']

# acumular columnas en una sola columna llamada Consultas
serieBS_examenes['Examenes'] = serieBS_examenes[cols_to_sum].sum(axis=1)

serieBS_examenes = (
    serieBS_examenes
    .groupby(
        ['IdServicio','Ano','IdEstablecimiento',
         'IdRegion','IdComuna'],
        as_index=False
    )['Examenes']
    .sum()
)

# cruzar serieA con hospitales según IdEstablecimiento
hospitales = pd.merge(hospitales, serieBS_examenes[['IdEstablecimiento', 'Examenes']], left_on='hospital_id', right_on='IdEstablecimiento', how='left')

# eliminar columna IdEstablecimiento
hospitales = hospitales.drop(columns=['IdEstablecimiento'])

C:\Users\roesc\AppData\Local\Temp\ipykernel_8664\2750403370.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  serieBS_examenes['Examenes'] = serieBS_examenes[cols_to_sum].sum(axis=1)

In [32]:
# reemplazar missing values por 0
hospitales = hospitales.fillna(0)